### PR TITLE
feat: add yt to talks

### PR DESCRIPTION
**Pull request by Cahllagerfeld**

### CODE REVIEW

**Review by nisarhassan12 — CHANGES_REQUESTED** [review]
Thanks, @Cahllagerfeld for working on this. 

Can you make it so that the talk cards are clickable as is the case for 2021 in the sidebar on stages and the schedule pages?

**Comment by Cahllagerfeld** [comment]
That's actually exactly the question I had, is not clickable, because the new version of the contents file isn't deployed yet, or is it because I need to make further changes 😅 I'll have a look into it again

**Comment by nisarhassan12** [comment]
> That's actually exactly the question I had

Ah sorry, my bad. You're right. It will hopefully work as expected once the Json is deployed. 

We just need to address https://github.com/gitpod-io/devxconf.org/pull/194#issuecomment-1119546332 and we're good to go here.

**Review by Cahllagerfeld — COMMENTED** [review]
I've added `Qecr3TQk87Q` as index-video for stage 2022, its the corresponding opening-video to devXConf 2021

**Comment by nisarhassan12** [comment]
Thanks @Cahllagerfeld LGTM 👍🏿

**Pull request merged**
