### PR TITLE
Get the site ready for tomorrows Launch. 

### PR DESCRIPTION
**Pull request by nisarhassan12**

### CODE REVIEW

**Comment by JohannesLandgraf** [comment]
Quick feedback

- [ ] Pictures are very low res, lets use higher res
- [ ] Check if all discord links work on Community etc

**Comment by ChristinFrohne** [comment]
Great, thanks @nisarhassan12 

Some more feedback:

- [ ] why are the pictures of such bad quality? Do you have struggles exporting them from Figma? Most pictures are taken from LinkedIn or Twitter and never had a really good resolution. Still, it should be fine for this size. 

- [ ] can you move the last three speakers to the center and move `more to be announced soon` further up (see mockup)?

- [ ] `see prospectus` button and `read report` button should have black font on hover

- [ ] the fixed navigation bar got huge. Why did you change it? Please reduce its height back to the earlier version
Bildschirmfoto 2021-04-08 um 09 45 20

**Comment by ChristinFrohne** [comment]
Here are the updated links for the community page:

announcements: https://discord.gg/qwqYzWkEfW
main track: https://discord.gg/JP9bWxNbwS
coffee machine: https://discord.gg/P3WkSBxeRZ
gitpod community: https://discord.gg/EWN5sNfNTw

**Comment by nisarhassan12** [comment]
> - [x]  Pictures are very low res, let's use higher res

>  why are the pictures of such bad quality? Do you have struggles exporting them from Figma? Most pictures are taken from LinkedIn or Twitter and never had a really good resolution. Still, it should be fine for this size.

Sorry, I don't know why they are of such a bad quality. Now instead of exporting from Figma, I have switched to use the one that @ChristinFrohne provided here https://drive.google.com/drive/u/3/folders/1O97rVsH3yhSler-ZhR-emj06MrEyR5cy. Does that look better? Thanks

**Comment by ChristinFrohne** [comment]
>Does they look better?

yes, much better. 

- [ ] Nader's image looks a bit overexposed. I adjusted that in Figma. Can you reduce the exposure with CSS as well?
- [ ] align the picture of Josh so that his head is not cut

**Comment by nisarhassan12** [comment]
> - []  Nader's image looks a bit overexposed. I adjusted that in Figma. Can you reduce the exposure with CSS as well?

No. I tried but it does not work well. I think it's an issue with the image itself. 
nader-dabit

**Review by ChristinFrohne — COMMENTED** [review]
- [ ] the link to Twitter is quite difficult to access. Could you use the orange outlines on hover that you created before and link the whole card? Hope that's not too much work, as the hover style already exists
Bildschirmfoto 2021-04-08 um 12 12 10

- [x] remove one `@babel`
Bildschirmfoto 2021-04-08 um 12 13 35

- [x] the Twitter link of Kyle is wrong. Correct one: https://twitter.com/kcqon

- [ ] the name and the role should always be in the same line. But this is not a crucial issue. You can also take this in a follow-up tomorrow

Bildschirmfoto 2021-04-08 um 12 14 52

Feel free to merge it directly after you addressed the feedback

**Review by ChristinFrohne — APPROVED** [review]
Looks great, thanks a lot!

**Pull request merged**
