### PR TITLE
update expo. 

### PR DESCRIPTION
**Pull request by nisarhassan12**

### CODE REVIEW

**Review by ChristinFrohne — COMMENTED** [review]
Nice! Here some feedback @nisarhassan12 
- [x] update the codesee logo (see google drive)
- [x] datadog is not confirmed yet. please delete the logo
- [x] each start-up logo should link to the provided link (CNCF: https://www.cncf.io Cloudquery:https://cloudquery.io)
- [x] each silver and gold sponsor should have a primary button (provided link) and a secondary button (discord link). Any additional links are listed under resources. If no additional links are provided, please delete the resources section
- [ ] raycast, codesee and slim.ai primary link is missing: https://raycast.com/?ref=devx-conf, https://www.slim.ai, www.codesee.io
- [ ] can we use a screenshot of their website if they didn't provide an image? The YouTube placeholder doesn't fit

- [ ] link from /home to each sponsor details. e.g. /expo/raycast

**Comment by nisarhassan12** [comment]
>  - [ ] update the codesee logo (see google drive)

The new updated logo does not look good:

image

**Comment by ChristinFrohne** [comment]
It should have the same style as all the other logos. Please use the file in google drive and align it to the style of the other logos e.g. a grey fill

**Comment by nisarhassan12** [comment]
Thanks. I tried to update the colours in Figma but I'm not able to do so. I don't know how I can change the colour of a PNG in Figma. The drive contains a PNG file. Would be nice if you can provide the SVG.

**Comment by nisarhassan12** [comment]
> - [ ] each start-up logo should link to the provided link (CNCF: https://www.cncf.io Cloudquery:https://cloudquery.io)

@ChristinFrohne  Did you mean the logo here? or inside of the expo detail page? 

image

**Comment by ChristinFrohne** [comment]
@nisarhassan12 Sorry if I haven't communicated this well. CodeSee sent me a new logo. That logo in .svg format is lying in google drive. Please update the old logo with the new one :)

**Comment by nisarhassan12** [comment]
> - [x]  link from /home to each sponsor details. e.g. /expo/raycast 

Some partners don't have a detailed expo page for instance CNFC and Cloud Query  for those I'm still linking to their sites.

**Review by ChristinFrohne — COMMENTED** [review]
- [ ] the link from /home to /expo/optic is not working
- [ ] on /expo the start-up sponsors should link to the provided link

Please merge it afterward

**Pull request merged**
