### PR TITLE
Go LIVE

### PR DESCRIPTION
**Pull request by ghuntley**
Merge this pull-request moments before the go-live to expose features to our audience. 

nb. Feel free to tack on small items into this branch. The idea is to have everything related to the conference already in production but hidden. Merging exposes the hidden features.

### CODE REVIEW

**Comment by nisarhassan12** [comment]
Now that there are 2 stages we need to have Stage A and B we need two links in the nav.

**Comment by mikenikles** [comment]
I added the two stages to the top nav. This causes the nav elements to wrap onto two lines. @nisarhassan12 could you widen the container a bit or possibly reducing the font size.

**Comment by nisarhassan12** [comment]
Thanks, @mikenikles I'm looking into it now.

**Comment by nisarhassan12** [comment]
@ChristinFrohne For now I have made the font size of the items smaller both on Desktop and mobile but that does not look good. Can we get rid of any of the nav items to make room i.e maybe we can remove the schedule as it is gonna be on the stages anyway.

**Comment by ChristinFrohne** [comment]
@nisarhassan12 do we need to have "Stage A" and "Stage B" in the navigation bar? Can not just have "stage" and a button to switch between stages similar to https://nextjs.org/2020/conf?

**Comment by nisarhassan12** [comment]
Thanks. @ChristinFrohne we can have that for sure. They don't have any link to the stage in the Nav should we also do that? if not which stage should we link to from the nav `A` or `B`? Thanks

**Comment by mikenikles** [comment]
#111 implements the multi-day, multi-stage schedule and the schedule dropdown on the stage page displays the two days rather than stages.

I suggest we add a note below the video that informs the viewer to switch to the other stage if the waiting video plays. On stage A, this should include a link to stage B and vice versa.

Given we're a few hours away, I recommend we keep code changes to an absolute minimum.

**Comment by ChristinFrohne** [comment]
@nisarhassan12 The looping of the starting-soon video is not working yet

**Pull request merged**
