### PR TITLE
add schedule.

### LINKED ISSUE #138: Add DevX Conf schedule
Once our schedule is finalised[[1](https://www.notion.so/gitpod/create-conference-schedule-495d2a222adb42ae81f30e0ac992be38)], we need to it to the website.

💭 I was looking at last year's design [[2](https://www.figma.com/file/Xsm95RBYugIxOc2bBaVvnF/DevX-Conf?node-id=35%3A1343)] and thought we could adopt a similar layout, apart from it being one video stream with the day schedule on the right-hand side? cc/ @chrifro any thoughts?

❓ Pre-conference, did you also have the schedule anywhere on the website? E.g. the landing page? Is this something we should consider this year?

Also tracking **[here (internal document)](https://www.notion.so/gitpod/Add-DevX-Conf-schedule-to-website-86236648566a49198ea96a4a917e30d0)**

### PR DESCRIPTION
**Pull request by nisarhassan12**
Fixes #138

### CODE REVIEW

**Comment by nisarhassan12** [comment]
@pawlean For the panel talk in the schedule What do think about leaving the avatars because 4 names with 4 avatars might look a bit too much? WDYT ? once we add the people in the panel as speakers I can show you how it might look and we can make the final call then. 

image

**Comment by pawlean** [comment]
@nisarhassan12 I'd remove (_moderator_) after Chad's name, by the way.

Yeah, let's see it with the 4 avatars and go from there 👀

**Comment by pawlean** [comment]
A few comments from me:

Mine and Michael's section should be at the end on both days.
2022-04-22 at 13 07 16 - Google Chrome@2x
2022-04-22 at 13 07 44 - Google Chrome@2x

Wrong person here.
2022-04-22 at 13 07 35 - Google Chrome@2x

The sessions should be separated by Tracks/Stages to make more clear.

**Comment by pawlean** [comment]
I would also separate the schedule out a bit / in new lines for both days. 💻 So something like this:

1. Intro and keynote
2. **Stage A:** all speakers
3. **Stage B:** all speakers
4. Finish for the day

 2022-04-22 at 13 12 48 - Google Chrome@2x

Difficult to explain but I hope it makes sense.

**Review by pawlean — CHANGES_REQUESTED** [review]
Apart from the comments above, it looks great!

**Comment by pawlean** [comment]
Thanks for the quick clarification sync, @nisarhassan12! 

As long as there is a clear distinction on Stages that is what matters 👍🏼

**Comment by pawlean** [comment]
**FYI:** Some slight changes to the schedule [here](https://www.notion.so/create-conference-schedule-495d2a222adb42ae81f30e0ac992be38?d=36956eba61a94018b955af38a95dc647#5bb4b1c247c346c0bc5684df3639e15b).

**Comment by pawlean** [comment]
Looks so much better. 🎊 Thank you @nisarhassan12! Quick thoughts:

- [ ] Can you switch around Tarun and Boris' talk around?
- [ ] Can you remove the "." in "The Next Generation of Developer-First Products"?
- [ ] For Keynote #1 - can we actually have "Remote development panel with Kirill Skrygan, Sven Efftinge, Nik Molnar, Johannes Landgraf? We'll have one more speaker but it's important to have at least one keynote there.
- [ ] For Chad's Panel can you change it to - DevX Past and Future?

**Review by pawlean — CHANGES_REQUESTED** [review]
LGTM, just the thoughts above ☝️

**Pull request merged**
